//! Generalized 3'-anchor candidate generation.
//!
//! Legacy BatchPrimer3 always forced a single-base SNP to be the primer's
//! 3'-terminal base. This module generalizes that rule to arbitrary-length
//! alleles (insertions, deletions, multi-base substitutions):
//!
//! ```text
//! anchor(allele) = variant_start + max(allele.len(), 1) - 1
//! ```
//!
//! - Non-empty allele: the anchor lands on the last base of the allele
//!   itself (collapses to the legacy rule when `len == 1`).
//! - Empty allele (deletion): the anchor falls back to `variant_start`,
//!   i.e. the first base of `right_flank` — so the primer necessarily spans
//!   the junction where `left_flank` glues directly to `right_flank`
//!   (diagnostic because on the other, longer allele those two bases are
//!   *not* adjacent).
//!
//! Reverse-oriented candidates are generated by reverse-complementing the
//! **whole** allele-substituted sequence as one string and mirroring the
//! anchor index, rather than re-deriving separate arithmetic — this avoids
//! the off-by-one risk of hand-writing a second, independent formula.

use crate::model::Orientation;
use crate::variant::Variant;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Candidate {
    pub sequence: String,
    pub orientation: Orientation,
    /// Offset of the candidate's leftmost original-coordinate base, minus
    /// `variant_start`. Computed in the *original* (non-reverse-complemented)
    /// coordinate frame for both orientations, so the two are comparable.
    pub pos_relative_to_variant: i64,
}

/// The 3'-anchor index (0-based, into the allele-substituted sequence) for
/// an allele of the given length.
pub fn anchor_index(variant_start: usize, allele_len: usize) -> usize {
    variant_start + allele_len.max(1) - 1
}

/// All windows of length `[min_len, max_len]` ending exactly at `anchor_idx`
/// (inclusive) in `seq`, skipping any window that would run off either end.
/// Returns `(start, substring)` pairs.
fn candidates_ending_at(
    seq: &str,
    anchor_idx: usize,
    min_len: usize,
    max_len: usize,
) -> Vec<(usize, String)> {
    let mut out = Vec::new();
    if anchor_idx >= seq.len() {
        return out;
    }
    for len in min_len..=max_len {
        if len == 0 || len > anchor_idx + 1 {
            continue;
        }
        let start = anchor_idx + 1 - len;
        let end = anchor_idx + 1;
        out.push((start, seq[start..end].to_string()));
    }
    out
}

/// Generates all forward- and reverse-oriented 3'-anchored candidates for
/// one allele of `variant`, with primer lengths in `[min_len, max_len]`.
pub fn generate_candidates(
    variant: &Variant,
    allele_idx: usize,
    min_len: usize,
    max_len: usize,
) -> Vec<Candidate> {
    let full = variant.full_seq(allele_idx);
    let variant_start = variant.variant_start();
    let allele_len = variant.alleles[allele_idx].len();
    let anchor_idx = anchor_index(variant_start, allele_len);

    let mut out = Vec::new();

    for (start, seq) in candidates_ending_at(&full, anchor_idx, min_len, max_len) {
        let offset = start as i64 - variant_start as i64;
        out.push(Candidate { sequence: seq, orientation: Orientation::Forward, pos_relative_to_variant: offset });
    }

    let rc_full = primer3::reverse_complement(&full);
    let rc_anchor = full.len() - 1 - anchor_idx;
    for (_rc_start, seq) in candidates_ending_at(&rc_full, rc_anchor, min_len, max_len) {
        // Every reverse candidate, regardless of length, maps back to an
        // original-coordinate span starting exactly at anchor_idx (see
        // module docs / tests for the derivation).
        let offset = anchor_idx as i64 - variant_start as i64;
        out.push(Candidate { sequence: seq, orientation: Orientation::Reverse, pos_relative_to_variant: offset });
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::variant::VariantSource;

    fn snp_variant(left: &str, alleles: &[&str], right: &str) -> Variant {
        Variant {
            left_flank: left.to_string(),
            right_flank: right.to_string(),
            alleles: alleles.iter().map(|s| s.to_string()).collect(),
            source: VariantSource::Bracket,
        }
    }

    #[test]
    fn anchor_index_snp_is_the_snp_position() {
        assert_eq!(anchor_index(10, 1), 10);
    }

    #[test]
    fn anchor_index_insertion_is_last_inserted_base() {
        // A 3-base insertion starting at variant_start=10 ends at index 12.
        assert_eq!(anchor_index(10, 3), 12);
    }

    #[test]
    fn anchor_index_deletion_falls_back_to_variant_start() {
        assert_eq!(anchor_index(10, 0), 10);
    }

    #[test]
    fn forward_candidate_exact_substring_snp() {
        // left="AAAACCCCGG" (10 bases), allele "T" (SNP), right="TTTTGGGGAA"
        let v = snp_variant("AAAACCCCGG", &["T", "A"], "TTTTGGGGAA");
        let cands = generate_candidates(&v, 0, 5, 5);
        let fwd: Vec<_> = cands.iter().filter(|c| c.orientation == Orientation::Forward).collect();
        assert_eq!(fwd.len(), 1);
        // full_seq = "AAAACCCCGG" + "T" + "TTTTGGGGAA", anchor at index 10 (the 'T')
        // length-5 window ending at index 10 (inclusive) = indices [6..11) = "CCGGT"
        assert_eq!(fwd[0].sequence, "CCGGT");
        assert_eq!(fwd[0].pos_relative_to_variant, -4); // start=6, variant_start=10 -> 6-10=-4
    }

    #[test]
    fn reverse_candidate_exact_substring_snp() {
        let v = snp_variant("AAAACCCCGG", &["T", "A"], "TTTTGGGGAA");
        let cands = generate_candidates(&v, 0, 5, 5);
        let rev: Vec<_> = cands.iter().filter(|c| c.orientation == Orientation::Reverse).collect();
        assert_eq!(rev.len(), 1);
        // full_seq = "AAAACCCCGGTTTTTGGGGAA" (21 chars): index0..9="AAAACCCCGG", index10='T', index11..20="TTTTGGGGAA"
        // rc(full_seq): reverse_complement of the whole 21-char string.
        let full = v.full_seq(0);
        assert_eq!(full, "AAAACCCCGGTTTTTGGGGAA");
        let rc_full = primer3::reverse_complement(&full);
        // anchor_idx=10 -> rc_anchor = 21-1-10 = 10
        // length-5 window ending at rc index 10 = rc_full[6..11)
        let expected = rc_full[6..11].to_string();
        assert_eq!(rev[0].sequence, expected);
        // Reverse candidate's original-coordinate offset is always anchor_idx - variant_start = 0
        assert_eq!(rev[0].pos_relative_to_variant, 0);
    }

    #[test]
    fn forward_candidate_exact_substring_insertion_allele() {
        // Insertion allele "ATT": anchor lands on the last inserted base ('T' at index 12).
        let v = snp_variant("AAAACCCCGG", &["A", "ATT"], "TTTTGGGGAA");
        let cands = generate_candidates(&v, 1, 6, 6);
        let fwd: Vec<_> = cands.iter().filter(|c| c.orientation == Orientation::Forward).collect();
        assert_eq!(fwd.len(), 1);
        // full_seq(1) = "AAAACCCCGG" + "ATT" + "TTTTGGGGAA" = "AAAACCCCGGATTTTTTGGGGAA"
        let full = v.full_seq(1);
        assert_eq!(full, "AAAACCCCGGATTTTTTGGGGAA");
        // anchor_idx = 10 + 3 - 1 = 12 (the second 'T' of "ATT")
        // length-6 window ending at index 12 (inclusive) = indices [7..13) = "CGGATT"
        assert_eq!(fwd[0].sequence, "CGGATT");
        assert_eq!(fwd[0].pos_relative_to_variant, -3); // start=7, variant_start=10 -> -3
    }

    #[test]
    fn forward_candidate_exact_substring_deletion_allele_spans_junction() {
        // Deletion allele "": anchor falls back to variant_start (10), the
        // first base of right_flank, so the window spans the junction.
        let v = snp_variant("AAAACCCCGG", &["AA", ""], "TTTTGGGGAA");
        let cands = generate_candidates(&v, 1, 6, 6);
        let fwd: Vec<_> = cands.iter().filter(|c| c.orientation == Orientation::Forward).collect();
        assert_eq!(fwd.len(), 1);
        // full_seq(1) = "AAAACCCCGG" + "" + "TTTTGGGGAA" = "AAAACCCCGGTTTTGGGGAA"
        let full = v.full_seq(1);
        assert_eq!(full, "AAAACCCCGGTTTTGGGGAA");
        // anchor_idx = 10 + max(0,1) - 1 = 10 (first 'T' of right_flank)
        // length-6 window ending at index 10 (inclusive) = indices [5..11) = "CCCGGT"
        assert_eq!(fwd[0].sequence, "CCCGGT");
        assert_eq!(fwd[0].pos_relative_to_variant, -5); // start=5, variant_start=10 -> -5
    }

    #[test]
    fn candidates_skip_lengths_that_would_run_off_the_sequence() {
        // variant_start=2, only 2 bases of left context available; a
        // length-5 window ending at the SNP (anchor_idx=2) needs 5 bases of
        // context before it and there are only 2, so it must be skipped.
        let v = snp_variant("AA", &["T", "A"], "TTTTTTTTTT");
        let cands = generate_candidates(&v, 0, 5, 5);
        assert!(cands.iter().all(|c| c.orientation != Orientation::Forward));
    }

    #[test]
    fn asymmetric_multi_base_substitution_anchors_on_last_base_of_each_allele() {
        // [AT/GCC]: allele 0 "AT" (len 2), allele 1 "GCC" (len 3) - different lengths, neither empty.
        let v = snp_variant("AAAACCCCGG", &["AT", "GCC"], "TTTTGGGGAA");

        let full0 = v.full_seq(0);
        assert_eq!(full0, "AAAACCCCGGATTTTTGGGGAA");
        // anchor_idx = 10 + 2 - 1 = 11 (the 'T' of "AT")
        let c0 = generate_candidates(&v, 0, 4, 4);
        let fwd0: Vec<_> = c0.iter().filter(|c| c.orientation == Orientation::Forward).collect();
        assert_eq!(fwd0[0].sequence, &full0[8..12]);
        assert_eq!(&full0[8..12], "GGAT");

        let full1 = v.full_seq(1);
        assert_eq!(full1, "AAAACCCCGGGCCTTTTGGGGAA");
        // anchor_idx = 10 + 3 - 1 = 12 (the last 'C' of "GCC")
        let c1 = generate_candidates(&v, 1, 4, 4);
        let fwd1: Vec<_> = c1.iter().filter(|c| c.orientation == Orientation::Forward).collect();
        assert_eq!(fwd1[0].sequence, &full1[9..13]);
        assert_eq!(&full1[9..13], "GGCC");
    }
}
