[package]
name = "peanutprimer3-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
peanutprimer3-core = { workspace = true }
eframe = { version = "0.35", features = ["glow"] }
egui = "0.35"
egui_extras = "0.35"
rfd = "0.17"
serde_json = { workspace = true }
